packages:
  - docs

allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false

peerDependencyRules:
  allowedVersions:
    # This can go once https://github.com/release-it/keep-a-changelog/pull/42 is merged
    "@release-it/keep-a-changelog>release-it": "20"
